apiVersion: v1
kind: Pod
metadata:
  name: poststart-pod
spec:
  containers:
  - name: my-container
    image: busybox
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello, PostStart Hook!"]
    command: ["/bin/sh", "-c", "sleep 3600"]
