apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:1.6.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config-map-jimmy
              mountPath: /etc/config
            - name: mosquitto-secret-jimmy
              mountPath: /etc/secret
      volumes:
        - name: mosquitto-config-map-jimmy
          configMap:
            name: mosquitto-config-file
        - name: mosquitto-secret-jimmy
          secret:
            secretName: mosquitto-secret-file
